### PR TITLE
Partial RedundantSensor (TPS, PPS); Monitoring (vs Averaging) mode

### PR DESCRIPTION
**Pull request by nmschulte**
I've tested these changes with Toyota ETCS-i ETB.  "Monitoring mode" causes RedundantSensor to track primary value, using secondary only to monitor for faults: this avoids stepwise transitions when using partial redundancy, allowing to avoid having to trim `tps1SecondarMax`/`tps2SecondaryMax`/`throttlePedalSecondarUpVoltage` values to [statically (in perfect environment)] compensate for 0.5% resolution of `tpsSecondaryMaximum`/`ppsSecondaryMaximum`.

Averaging (`tpsSecondaryMaximum`: `64.0`% [60.8% threshold @ 4.81325 V]; stepwise highlighted):
averages

Monitoring (`tpsSecondaryMaximum`: `64.0`% [60.8% threshold @ 4.81325 V]; stepwise eliminated)::
monitors

Branch includes updated `origin/master` merge.

### CODE REVIEW

**Comment by mck1117** [comment]
:eyes:
image

**Comment by nmschulte** [comment]
> Branch includes updated `origin/master` merge.

I can remove this, or you can update the target to include new `origin/master`.

**Comment by mck1117** [comment]
go ahead and merge mck1117:toyota-tps, should clean it up a bit

**Comment by nmschulte** [comment]
> go ahead and merge mck1117:toyota-tps, should clean it up a bit

done

**Pull request closed without merging**
